openapi: 3.0.0
info:
  title: Company Listings API
  version: 1.0.0
paths:
  /companies:
    get:
      summary: Get all companies
      responses:
        '200':
          description: A list of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    company_id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Company One
                    address:
                      type: string
                      example: 123 Main St
                    latitude:
                      type: number
                      format: float
                      example: 37.7749
                    longitude:
                      type: number
                      format: float
                      example: -122.4194
  /companies/{company_id}:
    get:
      summary: Get a company by ID
      parameters:
        - name: company_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A company object
          content:
            application/json:
              schema:
                type: object
                properties:
                  company_id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Company One
                  address:
                    type: string
                    example: 123 Main St
                  latitude:
                      type: number
                      format: float
                      example: 37.7749
                  longitude:
                      type: number
                      format: float
                      example: -122.4194
  /companies/{company_id}/locations:
    get:
      summary: Get locations for a company by ID
      parameters:
        - name: company_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of locations for the specified company
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    location_id:
                      type: integer
                      example: 1
                    company_id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Main Office
                    address:
                      type: string
                      example: 123 Main St
                    latitude:
                      type: number
                      format: float
                      example: 37.7749
                    longitude:
                      type: number
                      format: float
                      example: -122.4194
